<a href="https://colab.research.google.com/github/ShibleNK/ml-practice/blob/main/eval2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
X, y = np.arange(10).reshape((5,2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
y

range(0, 5)

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y , random_state=4)

In [ ]:
X_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [ ]:
y_train

[1, 4, 2]

In [ ]:
X_test

array([[0, 1],
       [6, 7]])

In [ ]:
y_test

[0, 3]

In [ ]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]

In [ ]:
# load iris dataset
from sklearn.datasets import load_iris
iris = load_iris()
# feature and target in X, y
X = iris.data
y =iris.target

In [ ]:
# watch array number before running tain_test_split
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [ ]:
# import train_test_split function
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(112, 4)
(38, 4)


In [ ]:
print(y_train.shape)
print(y_test.shape)

(112,)
(38,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [ ]:
# new X objects record
print(X_test.shape)
print(y_test.shape)

(60, 4)
(60,)


In [ ]:
# import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn =KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = knn.predict(X_test)
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667
